### ISSUE TITLE
No default max retry

### ISSUE THREAD

**Issue by jettcalleja** [anyTV/cuddle#22]
Based from https://github.com/anyTV/cuddle/blob/master/src/Request.js#L97, it has no default max_retry, but in README it shows the default max_retry is 3. Can we remove this documentation? Or update the code to have default of 3 max_retry.

**Comment by pandafox** [comment]
Let's update the document first to align with the implementation. Some libraries may not expect retry if not set.

**Comment by jettcalleja** [comment]
Created PR: https://github.com/anyTV/cuddle/pull/23

**Comment by jettcalleja** [comment]
Merged at https://github.com/anyTV/cuddle/commit/ecf0a5ca410666127f5cfd90bb36aa5a8f05232e
